language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
before_install:
  - rustup target add wasm32-unknown-unknown
script:
  - npm run build
  - cargo test --package status-message -- --nocapture